### ISSUE TITLE
[Question] A13-15 not usable for thermistors, with the Arduino DUE

### ISSUE THREAD

**Issue by GMagician** [MrAlvin/RAMPS-1.4.4#1]
On RepRap wiki you stated that A13-15 on due can't be used for thermistor..reason?
AFAIK these pins can works as analog input...

**Comment by GMagician** [comment]
From Marlin repo:

> Perhaps I could help with some ideas and test results?

everything is welcome... I just discovered now the big job you have done here...I'm sad for "ramps" like connectors you have used (I had overheating issues on stepper because of them, melted wires due to fake contacts that I solved replacing them with KF2510), otherwise this was good replacement board.

If you like to take a look you can find my job at https://github.com/GMagician/Ramps-EVO.
Heater page is just a draft, not chosen yet mosfet and buffer/pulldown resistor are missing.
Valid pages are main, endstops and thermistors

**Comment by MrAlvin** [comment]
If you take a look at this DUE pinout diagram (https://forum.arduino.cc/index.php?topic=132130.0) there are no A13-A15 options shown. 

And if you try to compile this test sketch, for DUE, you will get a compile error message about no A13 declared for DUE. 

int sense;
void setup() {
  sense = analogRead(A13);  
  sense = analogRead(A14);
  sense = analogRead(A15);
}
void loop() {
 // do nothing
}

**Comment by MrAlvin** [comment]
> From Marlin repo:
> 
> > Perhaps I could help with some ideas and test results?
> 
> everything is welcome... I just discovered now the big job you have done here...I'm sad for "ramps" like connectors you have used (I had overheating issues on stepper because of them, melted wires due to fake contacts that I solved replacing them with KF2510), otherwise this was good replacement board.
> 
> If you like to take a look you can find my job at https://github.com/GMagician/Ramps-EVO.
> Heater page is just a draft, not chosen yet mosfet and buffer/pulldown resistor are missing.
> Valid pages are main, endstops and thermistors

I agree that the KF2510 style connectors are much preferable, over the simple pin connectors. 

For RAMPS form-factor reasons, the 1.4.4 shield has however no room for the KF2510 style connectors. 

So I think that it would be good to also have a bigger RAMPS shield, with room for better connectors. 

It seems that the cheapest propper connectors are however  the JST style ones (more specifically JST XH connectors). So perhaps it would be wise to do a design where one could choose to use either KF2510 style  or JST style connectors?

**Comment by GMagician** [comment]
AFAIK KF2510 are  2.54mm pitch while JST XH are 2mm (even if thwey are often called JST XH 2.54)

**Comment by GMagician** [comment]
> And if you try to compile this test sketch, for DUE, you will get a compile error message about no A13 declared for DUE

weird, it seems thay can be used as AIN but I'll be surely wrong

**Comment by MrAlvin** [comment]
> AFAIK KF2510 are 2.54mm pitch while JST XH are 2mm (even if thwey are often called JST XH 2.54)

Ah yes, they are indeed not 2.54mm 
This page states that they are 2.5mm http://www.jst-mfg.com/product/detail_e.php?series=277

So I can see how they could be made to fit into 2.54mm PCB holes, and why ebay sellers call them 2.54mm. 

The JST web site even shows that they have no  2.54mm connectors - that are not also just pin comnectors. 
http://www.jst-mfg.com/product/search_e.php?type=1&id=1&page=4

**Comment by GMagician** [comment]
> JST XH are 2mm

oh yes sorry, 2,5
